image: registry.gitlab.com/kitsudaiki/kitsunemimi-ci-docker-images/opencl-tests:1.0.0


build:
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME

    - apt-get update
    - apt-get install -y libboost-filesystem-dev

    - cd /builds/kitsudaiki/libKitsunemimiOpencl
    - ./build.sh
    - clinfo
    - /builds/kitsudaiki/build/libKitsunemimiOpencl/tests/functional_tests/functional_tests

  tags:
    - docker
    - opencl
